version: "3.9"

services:
  site-7aylabs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: site-7aylabs
    restart: always
    environment:
      NODE_ENV: production
      HOSTNAME: 0.0.0.0
      PORT: 8082
    expose:
      - "8082"
    networks:
      - site_net

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    depends_on:
      - site-7aylabs
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - site_net
    restart: always

networks:
  site_net:
    driver: bridge
