
upstream site_7aylabs_upstream {
    server site-7aylabs-test:8082;
    keepalive 64;
}

server {
  listen 80;
  server_name _;

  location ~* \.(?:ico|css|js|gif|jpe?g|png|svg|webp|woff2?)$ {
    proxy_pass http://site_7aylabs_upstream;
    proxy_http_version 1.1;
    proxy_set_header Connection "";

    expires 4h;
    add_header Cache-Control "public, max-age=14400";

    types {
      image/svg+xml svg;
    }
  }

  location / {
    proxy_pass http://site_7aylabs_upstream;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
  }

 
  location /health {
    return 200 "ok";
    add_header Content-Type text/plain;
  }

 
  error_page 500 502 503 504 /50x.html;
  location = /50x.html { root /usr/share/nginx/html; }
}